### ISSUE TITLE
RPC started with kv but it not available from code

### ISSUE THREAD

**Issue by dehbka** [spiral/roadrunner-kv#25]
![image](https://user-images.githubusercontent.com/16839017/185910254-6e7f4e7a-19a3-4cd7-8202-3921b0a80664.png)

i create repository to reproduse issue https://github.com/dehbka/rr-kv

run [test-kv.php](https://github.com/dehbka/rr-kv/blob/master/test-kv.php) inside container

![image](https://user-images.githubusercontent.com/16839017/185910667-c871cc94-512b-4d67-b4dc-fcf31637263a.png)

What am I doing wrong?

**Comment by rustatian** [comment]
Hey @dehbka 👋🏻 
Don't use the `isAvailable` method. It's a no-op (but cause exception) and will be deleted soon.
